-- Constumer 360 data product 1

/*
This creates one row per customer with:

Lifetime Spend
Average Order Value
Purchase Frequency
Recency
Return Rate
Promotion Response
Customer Segment
*/

CREATE OR REPLACE TABLE CONSUMER.CUSTOMER_360 AS

WITH SALES_AGG AS (
    SELECT
        fs.CUSTOMER_KEY,

        COUNT(DISTINCT fs.ORDER_NUMBER) AS TOTAL_ORDERS,

        SUM(fs.NET_PAID) AS LIFETIME_SPEND,

        SUM(fs.NET_PROFIT) AS LIFETIME_PROFIT,

        SUM(fs.QUANTITY) AS TOTAL_ITEMS_PURCHASED,

        SUM(fs.EXT_DISCOUNT_AMT) AS TOTAL_DISCOUNT_AMOUNT,

        SUM(fs.COUPON_AMT) AS TOTAL_COUPON_AMOUNT,

        AVG(fs.NET_PAID) AS AVG_LINE_VALUE,

        SUM(fs.NET_PAID)
            / NULLIF(COUNT(DISTINCT fs.ORDER_NUMBER), 0) AS AVERAGE_ORDER_VALUE,

        COUNT(DISTINCT fs.ORDER_NUMBER) AS PURCHASE_FREQUENCY,

        MAX(dd.D_DATE) AS LAST_PURCHASE_DATE,

        DATEDIFF(
            DAY,
            MAX(dd.D_DATE),
            CURRENT_DATE()
        ) AS RECENCY_DAYS,

        COUNT(DISTINCT CASE
            WHEN fs.PROMOTION_KEY IS NOT NULL THEN fs.ORDER_NUMBER
        END) AS PROMOTION_ORDERS,

        COUNT(DISTINCT CASE
            WHEN fs.PROMOTION_KEY IS NOT NULL THEN fs.ORDER_NUMBER
        END)
            / NULLIF(COUNT(DISTINCT fs.ORDER_NUMBER), 0) AS PROMOTION_RESPONSE_RATE

    FROM MODELLED.FACT_SALES fs

    LEFT JOIN MODELLED.DIM_DATE dd
        ON fs.DATE_KEY = dd.D_DATE_SK

    GROUP BY
        fs.CUSTOMER_KEY
),

RETURNS_AGG AS (
    SELECT
        fr.CUSTOMER_KEY,

        COUNT(DISTINCT fr.RETURN_NUMBER) AS TOTAL_RETURNS,

        SUM(fr.RETURN_AMT) AS TOTAL_RETURN_AMOUNT,

        SUM(fr.RETURN_QUANTITY) AS TOTAL_RETURN_QUANTITY

    FROM MODELLED.FACT_RETURNS fr

    GROUP BY
        fr.CUSTOMER_KEY
),

CUSTOMER_ACTIVITY_AGG AS (
    SELECT
        fca.CUSTOMER_KEY,

        SUM(fca.ORDER_COUNT) AS ACTIVITY_ORDER_COUNT,

        SUM(fca.TOTAL_SPEND) AS ACTIVITY_TOTAL_SPEND,

        SUM(fca.TOTAL_PROFIT) AS ACTIVITY_TOTAL_PROFIT,

        SUM(fca.RETURN_COUNT) AS ACTIVITY_RETURN_COUNT,

        SUM(fca.RETURN_AMOUNT) AS ACTIVITY_RETURN_AMOUNT,

        SUM(fca.NET_SPEND) AS ACTIVITY_NET_SPEND

    FROM MODELLED.FACT_CUSTOMER_ACTIVITY fca

    GROUP BY
        fca.CUSTOMER_KEY
)

SELECT
    dc.C_CUSTOMER_SK AS CUSTOMER_KEY,
    dc.C_CUSTOMER_ID AS CUSTOMER_ID,

    CONCAT(
        COALESCE(dc.C_FIRST_NAME, ''),
        ' ',
        COALESCE(dc.C_LAST_NAME, '')
    ) AS CUSTOMER_NAME,

    dc.C_EMAIL_ADDRESS,
    dc.CUSTOMER_AGE,
    dc.AGE_GROUP,
    dc.CD_GENDER,
    dc.CD_MARITAL_STATUS,
    dc.CD_EDUCATION_STATUS,
    dc.CD_CREDIT_RATING,
    dc.INCOME_BAND,
    dc.HD_BUY_POTENTIAL,
    dc.CA_CITY,
    dc.CA_STATE,
    dc.CA_COUNTRY,

    COALESCE(sa.TOTAL_ORDERS, 0) AS TOTAL_ORDERS,
    COALESCE(sa.LIFETIME_SPEND, 0) AS LIFETIME_SPEND,
    COALESCE(sa.LIFETIME_PROFIT, 0) AS LIFETIME_PROFIT,
    COALESCE(sa.TOTAL_ITEMS_PURCHASED, 0) AS TOTAL_ITEMS_PURCHASED,
    COALESCE(sa.TOTAL_DISCOUNT_AMOUNT, 0) AS TOTAL_DISCOUNT_AMOUNT,
    COALESCE(sa.TOTAL_COUPON_AMOUNT, 0) AS TOTAL_COUPON_AMOUNT,

    COALESCE(sa.AVERAGE_ORDER_VALUE, 0) AS AVERAGE_ORDER_VALUE,

    COALESCE(sa.PURCHASE_FREQUENCY, 0) AS PURCHASE_FREQUENCY,

    sa.LAST_PURCHASE_DATE,

    sa.RECENCY_DAYS,

    COALESCE(ra.TOTAL_RETURNS, 0) AS TOTAL_RETURNS,
    COALESCE(ra.TOTAL_RETURN_AMOUNT, 0) AS TOTAL_RETURN_AMOUNT,
    COALESCE(ra.TOTAL_RETURN_QUANTITY, 0) AS TOTAL_RETURN_QUANTITY,

    COALESCE(ra.TOTAL_RETURNS, 0)
        / NULLIF(COALESCE(sa.TOTAL_ORDERS, 0), 0) AS RETURN_RATE,

    COALESCE(sa.PROMOTION_ORDERS, 0) AS PROMOTION_ORDERS,

    COALESCE(sa.PROMOTION_RESPONSE_RATE, 0) AS PROMOTION_RESPONSE_RATE,

    COALESCE(caa.ACTIVITY_ORDER_COUNT, 0) AS ACTIVITY_ORDER_COUNT,
    COALESCE(caa.ACTIVITY_TOTAL_SPEND, 0) AS ACTIVITY_TOTAL_SPEND,
    COALESCE(caa.ACTIVITY_TOTAL_PROFIT, 0) AS ACTIVITY_TOTAL_PROFIT,
    COALESCE(caa.ACTIVITY_RETURN_COUNT, 0) AS ACTIVITY_RETURN_COUNT,
    COALESCE(caa.ACTIVITY_RETURN_AMOUNT, 0) AS ACTIVITY_RETURN_AMOUNT,
    COALESCE(caa.ACTIVITY_NET_SPEND, 0) AS ACTIVITY_NET_SPEND,
    CURRENT_TIMESTAMP() AS REFRESH_TIMESTAMP

FROM MODELLED.DIM_CUSTOMER dc

LEFT JOIN SALES_AGG sa
    ON dc.C_CUSTOMER_SK = sa.CUSTOMER_KEY

LEFT JOIN RETURNS_AGG ra
    ON dc.C_CUSTOMER_SK = ra.CUSTOMER_KEY

LEFT JOIN CUSTOMER_ACTIVITY_AGG caa
    ON dc.C_CUSTOMER_SK = caa.CUSTOMER_KEY;

/*Some of these returns don't perfectly match to a sale, so only the ones that do were calculated */

/* Days to Return was calculated by matching return rows to sales rows using return/order number,
customer key, and product key. This avoids many-to-many duplication at order level. 
Where no product-level match was found, the return was retained in the returns metrics but excluded from the days-to-return average. */

/*
- Return Percentage 
- Return Frequency 
- Return Value 
- Days To Return
*/

CREATE OR REPLACE TABLE CONSUMER.RETURNS_INTELLIGENCE AS

WITH SALES_BASE AS (
    SELECT
        fs.ORDER_NUMBER,
        fs.CUSTOMER_KEY,
        fs.PRODUCT_KEY,

        MIN(fs.DATE_KEY) AS SALE_DATE_KEY,
        MIN(dd.D_DATE) AS SALE_DATE,

        SUM(fs.NET_PAID) AS SALES_VALUE,
        SUM(fs.NET_PROFIT) AS SALES_PROFIT,
        SUM(fs.QUANTITY) AS SALES_QUANTITY

    FROM MODELLED.FACT_SALES fs

    LEFT JOIN MODELLED.DIM_DATE dd
        ON fs.DATE_KEY = dd.D_DATE_SK

    GROUP BY
        fs.ORDER_NUMBER,
        fs.CUSTOMER_KEY,
        fs.PRODUCT_KEY
),

RETURNS_BASE AS (
    SELECT
        fr.RETURN_NUMBER,
        fr.CUSTOMER_KEY,
        fr.PRODUCT_KEY,

        fr.STORE_KEY,
        fr.REASON_KEY,
        fr.RETURN_CHANNEL,

        fr.DATE_KEY AS RETURN_DATE_KEY,
        dd.D_DATE AS RETURN_DATE,

        fr.RETURN_QUANTITY,
        fr.RETURN_AMT,
        fr.RETURN_TAX,
        fr.RETURN_AMT_INC_TAX,
        fr.FEE,
        fr.RETURN_SHIP_COST,
        fr.REFUNDED_CASH,
        fr.REVERSED_CHARGE,
        fr.ACCOUNT_CREDIT,
        fr.NET_LOSS

    FROM MODELLED.FACT_RETURNS fr

    LEFT JOIN MODELLED.DIM_DATE dd
        ON fr.DATE_KEY = dd.D_DATE_SK
),

MATCHED_RETURNS AS (
    SELECT
        rb.RETURN_NUMBER,
        rb.CUSTOMER_KEY,
        rb.PRODUCT_KEY,

        rb.STORE_KEY AS RETURN_STORE_KEY,
        rb.REASON_KEY,
        rb.RETURN_CHANNEL,

        rb.RETURN_DATE_KEY,
        rb.RETURN_DATE,

        rb.RETURN_QUANTITY,
        rb.RETURN_AMT,
        rb.RETURN_TAX,
        rb.RETURN_AMT_INC_TAX,
        rb.FEE,
        rb.RETURN_SHIP_COST,
        rb.REFUNDED_CASH,
        rb.REVERSED_CHARGE,
        rb.ACCOUNT_CREDIT,
        rb.NET_LOSS,

        sb.ORDER_NUMBER AS MATCHED_ORDER_NUMBER,
        sb.SALE_DATE_KEY,
        sb.SALE_DATE,

        CASE
            WHEN sb.ORDER_NUMBER IS NOT NULL
            THEN DATEDIFF(DAY, sb.SALE_DATE, rb.RETURN_DATE)
            ELSE NULL
        END AS DAYS_TO_RETURN,

        CASE
            WHEN sb.ORDER_NUMBER IS NOT NULL THEN 'Matched'
            ELSE 'Unmatched'
        END AS RETURN_MATCH_STATUS

    FROM RETURNS_BASE rb

    LEFT JOIN SALES_BASE sb
        ON rb.RETURN_NUMBER = sb.ORDER_NUMBER
       AND rb.CUSTOMER_KEY = sb.CUSTOMER_KEY
       AND rb.PRODUCT_KEY = sb.PRODUCT_KEY
),

SALES_AGG AS (
    SELECT
        CUSTOMER_KEY,

        COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS,

        SUM(SALES_VALUE) AS TOTAL_SALES_VALUE,

        SUM(SALES_QUANTITY) AS TOTAL_SALES_QUANTITY

    FROM SALES_BASE

    GROUP BY
        CUSTOMER_KEY
),

RETURNS_AGG AS (
    SELECT
        CUSTOMER_KEY,

        COUNT(DISTINCT RETURN_NUMBER) AS RETURN_FREQUENCY,

        COUNT(*) AS RETURN_LINE_COUNT,

        SUM(RETURN_QUANTITY) AS TOTAL_RETURN_QUANTITY,

        SUM(RETURN_AMT) AS RETURN_VALUE,

        SUM(RETURN_AMT_INC_TAX) AS RETURN_VALUE_INC_TAX,

        SUM(FEE) AS TOTAL_RETURN_FEES,

        SUM(RETURN_SHIP_COST) AS TOTAL_RETURN_SHIP_COST,

        SUM(REFUNDED_CASH) AS TOTAL_REFUNDED_CASH,

        SUM(REVERSED_CHARGE) AS TOTAL_REVERSED_CHARGE,

        SUM(ACCOUNT_CREDIT) AS TOTAL_ACCOUNT_CREDIT,

        SUM(NET_LOSS) AS TOTAL_NET_LOSS,

        COUNT(CASE
            WHEN RETURN_MATCH_STATUS = 'Matched' THEN 1
        END) AS MATCHED_RETURN_LINES,

        COUNT(CASE
            WHEN RETURN_MATCH_STATUS = 'Unmatched' THEN 1
        END) AS UNMATCHED_RETURN_LINES,

        COUNT(DISTINCT CASE
            WHEN RETURN_MATCH_STATUS = 'Matched'
            THEN MATCHED_ORDER_NUMBER
        END) AS MATCHED_RETURNED_ORDERS,

        AVG(DAYS_TO_RETURN) AS AVG_DAYS_TO_RETURN,

        MIN(DAYS_TO_RETURN) AS MIN_DAYS_TO_RETURN,

        MAX(DAYS_TO_RETURN) AS MAX_DAYS_TO_RETURN

    FROM MATCHED_RETURNS

    GROUP BY
        CUSTOMER_KEY
)

SELECT
    dc.C_CUSTOMER_SK AS CUSTOMER_KEY,
    dc.C_CUSTOMER_ID AS CUSTOMER_ID,

    CONCAT(
        COALESCE(dc.C_FIRST_NAME, ''),
        ' ',
        COALESCE(dc.C_LAST_NAME, '')
    ) AS CUSTOMER_NAME,

    dc.C_EMAIL_ADDRESS,
    dc.AGE_GROUP,
    dc.CD_GENDER,
    dc.CD_MARITAL_STATUS,
    dc.CD_CREDIT_RATING,
    dc.INCOME_BAND,
    dc.CA_CITY,
    dc.CA_STATE,
    dc.CA_COUNTRY,

    COALESCE(sa.TOTAL_ORDERS, 0) AS TOTAL_ORDERS,

    COALESCE(ra.RETURN_FREQUENCY, 0) AS RETURN_FREQUENCY,

    COALESCE(ra.RETURN_LINE_COUNT, 0) AS RETURN_LINE_COUNT,

    COALESCE(ra.RETURN_FREQUENCY, 0)
        / NULLIF(COALESCE(sa.TOTAL_ORDERS, 0), 0) AS RETURN_PERCENTAGE,

    COALESCE(ra.RETURN_VALUE, 0) AS RETURN_VALUE,

    COALESCE(ra.RETURN_VALUE_INC_TAX, 0) AS RETURN_VALUE_INC_TAX,

    COALESCE(ra.TOTAL_RETURN_QUANTITY, 0) AS TOTAL_RETURN_QUANTITY,

    COALESCE(ra.TOTAL_RETURN_FEES, 0) AS TOTAL_RETURN_FEES,

    COALESCE(ra.TOTAL_RETURN_SHIP_COST, 0) AS TOTAL_RETURN_SHIP_COST,

    COALESCE(ra.TOTAL_REFUNDED_CASH, 0) AS TOTAL_REFUNDED_CASH,

    COALESCE(ra.TOTAL_REVERSED_CHARGE, 0) AS TOTAL_REVERSED_CHARGE,

    COALESCE(ra.TOTAL_ACCOUNT_CREDIT, 0) AS TOTAL_ACCOUNT_CREDIT,

    COALESCE(ra.TOTAL_NET_LOSS, 0) AS TOTAL_NET_LOSS,

    COALESCE(sa.TOTAL_SALES_VALUE, 0) AS TOTAL_SALES_VALUE,

    COALESCE(ra.RETURN_VALUE, 0)
        / NULLIF(COALESCE(sa.TOTAL_SALES_VALUE, 0), 0) AS RETURN_VALUE_RATE,

    ra.AVG_DAYS_TO_RETURN,

    ra.MIN_DAYS_TO_RETURN,

    ra.MAX_DAYS_TO_RETURN,

    COALESCE(ra.MATCHED_RETURN_LINES, 0) AS MATCHED_RETURN_LINES,

    COALESCE(ra.UNMATCHED_RETURN_LINES, 0) AS UNMATCHED_RETURN_LINES,

    COALESCE(ra.MATCHED_RETURNED_ORDERS, 0) AS MATCHED_RETURNED_ORDERS,

    COALESCE(ra.MATCHED_RETURN_LINES, 0)
        / NULLIF(COALESCE(ra.RETURN_LINE_COUNT, 0), 0) AS RETURN_MATCH_RATE,

    CASE
        WHEN COALESCE(ra.RETURN_FREQUENCY, 0) = 0 THEN 'No Returns'

        WHEN COALESCE(ra.RETURN_FREQUENCY, 0)
             / NULLIF(COALESCE(sa.TOTAL_ORDERS, 0), 0) >= 0.50
        THEN 'High Return Behaviour'

        WHEN COALESCE(ra.RETURN_FREQUENCY, 0)
             / NULLIF(COALESCE(sa.TOTAL_ORDERS, 0), 0) >= 0.20
        THEN 'Medium Return Behaviour'

        ELSE 'Low Return Behaviour'
    END AS RETURN_BEHAVIOUR_SEGMENT,

    CURRENT_TIMESTAMP() AS REFRESH_TIMESTAMP

FROM MODELLED.DIM_CUSTOMER dc

LEFT JOIN SALES_AGG sa
    ON dc.C_CUSTOMER_SK = sa.CUSTOMER_KEY

LEFT JOIN RETURNS_AGG ra
    ON dc.C_CUSTOMER_SK = ra.CUSTOMER_KEY;

-- Data Product 4 Customer Value Segmentation

CREATE OR REPLACE TABLE CONSUMER.CUSTOMER_SEGMENTATION AS

WITH SPEND_RANKS AS (

    SELECT
        c.*,

        NTILE(100) OVER (
            ORDER BY LIFETIME_SPEND DESC
        ) AS SPEND_RANK_BUCKET

    FROM CONSUMER.CUSTOMER_360 c

)

SELECT

    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,

    LIFETIME_SPEND,
    PURCHASE_FREQUENCY,
    RECENCY_DAYS,

    CASE
        WHEN SPEND_RANK_BUCKET <= 5
            THEN 'Platinum'
        WHEN SPEND_RANK_BUCKET <= 20
            THEN 'Gold'
        WHEN SPEND_RANK_BUCKET <= 50
            THEN 'Silver'
        WHEN LIFETIME_SPEND > 0
            THEN 'Bronze'
        ELSE 'No Purchase'
    END AS CUSTOMER_VALUE_SEGMENT

FROM SPEND_RANKS;
-- I don't need a dormancy count because a lot of the dates are from 20 years ago



select *
from customer_360
limit 100;

select *
from returns_intelligence;

select *
from customer_segmentation
limit 5000;

-- region_store_performance

CREATE OR REPLACE TABLE CONSUMER.REGION_STORE_PERFORMANCE AS

WITH SALES_AGG AS (
    SELECT
        STORE_KEY,
        COUNT(DISTINCT ORDER_NUMBER) AS TOTAL_ORDERS,
        COUNT(DISTINCT CUSTOMER_KEY) AS CUSTOMER_COUNT,
        SUM(NET_PAID) AS TOTAL_SALES,
        SUM(NET_PROFIT) AS TOTAL_PROFIT,
        SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD,
        AVG(NET_PAID) AS AVG_LINE_VALUE,
        SUM(NET_PAID)
            / NULLIF(COUNT(DISTINCT ORDER_NUMBER), 0)
            AS AVG_ORDER_VALUE
    FROM MODELLED.FACT_SALES
    GROUP BY STORE_KEY
),

RETURNS_AGG AS (
    SELECT
        STORE_KEY,
        COUNT(DISTINCT RETURN_NUMBER) AS RETURN_COUNT,
        SUM(RETURN_AMT) AS RETURN_VALUE,
        SUM(RETURN_QUANTITY) AS RETURN_QUANTITY
    FROM MODELLED.FACT_RETURNS
    GROUP BY STORE_KEY
)

SELECT
    ds.STORE_KEY,
    ds.STORE_ID,
    ds.STORE_NAME,
    ds.STORE_MANAGER,

    COALESCE(dr.REGION, 'UNKNOWN') AS REGION,
    COALESCE(dr.COUNTRY, 'United States') AS COUNTRY,
    COALESCE(dr.STATE, 'UNKNOWN') AS STATE,
    COALESCE(dr.COUNTY, 'UNKNOWN') AS COUNTY,

    ds.STORE_SIZE,
    ds.FLOOR_SPACE_CATEGORY,
    ds.EMPLOYEE_COUNT,
    ds.FLOOR_SPACE_SQFT,
    ds.STORE_AGE_YEARS,

    COALESCE(sa.TOTAL_ORDERS, 0) AS TOTAL_ORDERS,
    COALESCE(sa.CUSTOMER_COUNT, 0) AS CUSTOMER_COUNT,
    COALESCE(sa.TOTAL_SALES, 0) AS TOTAL_SALES,
    COALESCE(sa.TOTAL_PROFIT, 0) AS TOTAL_PROFIT,
    COALESCE(sa.TOTAL_QUANTITY_SOLD, 0) AS TOTAL_QUANTITY_SOLD,
    COALESCE(sa.AVG_ORDER_VALUE, 0) AS AVG_ORDER_VALUE,

    COALESCE(ra.RETURN_COUNT, 0) AS RETURN_COUNT,
    COALESCE(ra.RETURN_VALUE, 0) AS RETURN_VALUE,
    COALESCE(ra.RETURN_QUANTITY, 0) AS RETURN_QUANTITY,

    COALESCE(ra.RETURN_COUNT, 0)
        / NULLIF(COALESCE(sa.TOTAL_ORDERS, 0), 0)
        AS RETURN_RATE,

    COALESCE(sa.TOTAL_SALES, 0)
        / NULLIF(ds.EMPLOYEE_COUNT, 0)
        AS SALES_PER_EMPLOYEE,

    COALESCE(sa.TOTAL_PROFIT, 0)
        / NULLIF(ds.EMPLOYEE_COUNT, 0)
        AS PROFIT_PER_EMPLOYEE,

    COALESCE(sa.TOTAL_SALES, 0)
        / NULLIF(ds.FLOOR_SPACE_SQFT, 0)
        AS SALES_PER_SQFT,

    CURRENT_TIMESTAMP() AS REFRESH_TIMESTAMP

FROM MODELLED.DIM_STORE ds

LEFT JOIN MODELLED.DIM_REGION dr
    ON COALESCE(ds.COUNTRY, 'United States') = dr.COUNTRY
   AND COALESCE(ds.STATE, 'UNKNOWN') = dr.STATE
   AND COALESCE(ds.COUNTY, 'UNKNOWN') = dr.COUNTY

LEFT JOIN SALES_AGG sa
    ON ds.STORE_KEY = sa.STORE_KEY

LEFT JOIN RETURNS_AGG ra
    ON ds.STORE_KEY = ra.STORE_KEY;

-- product performance for perfomance info

CREATE OR REPLACE TABLE CONSUMER.PRODUCT_PERFORMANCE AS

WITH SALES_AGG AS (
    SELECT
        fs.PRODUCT_KEY,
        COUNT(DISTINCT fs.ORDER_NUMBER) AS ORDERS_CONTAINING_PRODUCT,
        SUM(fs.QUANTITY) AS TOTAL_UNITS_SOLD,
        SUM(fs.NET_PAID) AS TOTAL_REVENUE,
        SUM(fs.NET_PROFIT) AS TOTAL_PROFIT
    FROM MODELLED.FACT_SALES fs
    GROUP BY fs.PRODUCT_KEY
),

RETURNS_AGG AS (
    SELECT
        fr.PRODUCT_KEY,
        COUNT(DISTINCT fr.RETURN_NUMBER) AS RETURN_COUNT,
        SUM(fr.RETURN_QUANTITY) AS RETURNED_UNITS,
        SUM(fr.RETURN_AMT) AS RETURN_VALUE
    FROM MODELLED.FACT_RETURNS fr
    GROUP BY fr.PRODUCT_KEY
)

SELECT
    dp.ITEM_SK AS PRODUCT_KEY,
    dp.ITEM_ID,
    dp.PRODUCT_NAME,
    dp.CATEGORY,
    dp.CLASS,
    dp.BRAND,
    dp.CURRENT_PRICE,
    dp.WHOLESALE_COST,

    COALESCE(sa.TOTAL_UNITS_SOLD, 0) AS TOTAL_UNITS_SOLD,
    COALESCE(sa.ORDERS_CONTAINING_PRODUCT, 0) AS ORDERS_CONTAINING_PRODUCT,
    COALESCE(sa.TOTAL_REVENUE, 0) AS TOTAL_REVENUE,
    COALESCE(sa.TOTAL_PROFIT, 0) AS TOTAL_PROFIT,

    COALESCE(sa.TOTAL_PROFIT, 0)
        / NULLIF(COALESCE(sa.TOTAL_REVENUE, 0), 0) AS PROFIT_MARGIN,

    -- return transactions
    COALESCE(ra.RETURN_COUNT, 0) AS RETURN_COUNT,
    -- returned units
    COALESCE(ra.RETURNED_UNITS, 0) AS RETURNED_UNITS,
    COALESCE(ra.RETURN_VALUE, 0) AS RETURN_VALUE,

    COALESCE(ra.RETURNED_UNITS, 0)
        / NULLIF(COALESCE(sa.TOTAL_UNITS_SOLD, 0), 0) AS RETURN_RATE,

    CURRENT_TIMESTAMP() AS REFRESH_TIMESTAMP

FROM MODELLED.DIM_PRODUCT dp

LEFT JOIN SALES_AGG sa
    ON dp.ITEM_SK = sa.PRODUCT_KEY

LEFT JOIN RETURNS_AGG ra
    ON dp.ITEM_SK = ra.PRODUCT_KEY;

CREATE OR REPLACE TABLE CONSUMER.SALES_TIME_CHANNEL_PERFORMANCE AS

SELECT
    fs.DATE_KEY,
    fs.SALES_CHANNEL,

    dd.D_DATE,
    dd.D_YEAR,
    dd.MONTH_NUMBER,
    dd.MONTH_NAME,
    dd.QUARTER_OF_YEAR,
    dd.YEAR_QUARTER,
    dd.YEAR_MONTH,
    dd.DAY_OF_WEEK,
    dd.D_DAY_NAME,
    dd.DAY_TYPE,
    dd.SEASON,

    COUNT(DISTINCT fs.ORDER_NUMBER) AS TOTAL_ORDERS,
    COUNT(DISTINCT fs.CUSTOMER_KEY) AS CUSTOMER_COUNT,
    SUM(fs.QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(fs.NET_PAID) AS TOTAL_SALES,
    SUM(fs.NET_PROFIT) AS TOTAL_PROFIT,

    SUM(fs.NET_PAID)
        / NULLIF(COUNT(DISTINCT fs.ORDER_NUMBER), 0) AS AVG_ORDER_VALUE,

    SUM(fs.QUANTITY)
        / NULLIF(COUNT(DISTINCT fs.ORDER_NUMBER), 0) AS AVG_ITEMS_PER_ORDER,

    CURRENT_TIMESTAMP() AS REFRESH_TIMESTAMP

FROM MODELLED.FACT_SALES fs

LEFT JOIN MODELLED.DIM_DATE dd
    ON fs.DATE_KEY = dd.D_DATE_SK

GROUP BY
    fs.DATE_KEY,
    fs.SALES_CHANNEL,
    dd.D_DATE,
    dd.D_YEAR,
    dd.MONTH_NUMBER,
    dd.MONTH_NAME,
    dd.QUARTER_OF_YEAR,
    dd.YEAR_QUARTER,
    dd.YEAR_MONTH,
    dd.DAY_OF_WEEK,
    dd.D_DAY_NAME,
    dd.DAY_TYPE,
    dd.SEASON;

select *
from sales_time_channel_performance;
select *
from region_store_performance;

select *
from product_performance;

select *
from customer_360;

SHOW TABLES IN SCHEMA CONSUMER;