CREATE OR REPLACE TABLE RAW_CUSTOMER (
    C_CUSTOMER_SK NUMBER,
    C_CUSTOMER_ID STRING,
    C_CURRENT_CDEMO_SK NUMBER,
    C_CURRENT_HDEMO_SK NUMBER,
    C_CURRENT_ADDR_SK NUMBER,
    C_FIRST_SHIPTO_DATE_SK NUMBER,
    C_FIRST_SALES_DATE_SK NUMBER,
    C_SALUTATION STRING,
    C_FIRST_NAME STRING,
    C_LAST_NAME STRING,
    C_PREFERRED_CUST_FLAG STRING,
    C_BIRTH_DAY NUMBER,
    C_BIRTH_MONTH NUMBER,
    C_BIRTH_YEAR NUMBER,
    C_BIRTH_COUNTRY STRING,
    C_LOGIN STRING,
    C_EMAIL_ADDRESS STRING,
    C_LAST_REVIEW_DATE DATE,

    LOAD_ID STRING,
    LOAD_DATE TIMESTAMP,
    SOURCE_FILE_NAME STRING,
    BATCH_ID STRING
);

SET LOAD_ID = UUID_STRING();
SET BATCH_ID = '2026W01';




DESC TABLE CUSTOMER;
FILE_FORMAT = (FORMAT_NAME = STAGE.CSV_FORMAT);

SELECT COUNT(*)
FROM RAW_CUSTOMER;

describe table customer;

SELECT *
FROM @STAGE.CUSTOMER_STAGE
(FILE_FORMAT => STAGE.CSV_FORMAT);


INSERT INTO RAW_CUSTOMER
SELECT
    *,
    UUID_STRING(),
    CURRENT_TIMESTAMP(),
    'CUSTOMER_SOURCE',
    '2026W01'
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER
LIMIT 100000;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(C_CUSTOMER_SK IS NULL) AS NULL_CUSTOMER_SK,
    COUNT_IF(C_CUSTOMER_ID IS NULL) AS NULL_CUSTOMER_ID,
    COUNT_IF(C_CURRENT_CDEMO_SK IS NULL) AS NULL_CDEMO_SK,
    COUNT_IF(C_CURRENT_HDEMO_SK IS NULL) AS NULL_HDEMO_SK,
    COUNT_IF(C_CURRENT_ADDR_SK IS NULL) AS NULL_ADDR_SK,
    COUNT_IF(C_FIRST_NAME IS NULL) AS NULL_FIRST_NAME,
    COUNT_IF(C_LAST_NAME IS NULL) AS NULL_LAST_NAME,
    COUNT_IF(C_EMAIL_ADDRESS IS NULL) AS NULL_EMAIL
FROM RAW_CUSTOMER;

CREATE OR REPLACE TABLE RAW_CUSTOMER_ADDRESS AS
SELECT
    *,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    'CUSTOMER_ADDRESS_SOURCE' AS SOURCE_FILE_NAME,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_ADDRESS;
LIMIT 10000;

select * from Raw_customer_address;


CREATE OR REPLACE TABLE RAW_INCOME_BAND AS
SELECT
    *,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    'INCOME_BAND_SOURCE' AS SOURCE_FILE_NAME,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.INCOME_BAND
LIMIT 10000;

select * from raw_income_band;



CREATE OR REPLACE TABLE RAW_HOUSEHOLD_DEMOGRAPHICS AS
SELECT
    *,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    'HOUSEHOLD_DEMOGRAPHICS_SOURCE' AS SOURCE_FILE_NAME,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.HOUSEHOLD_DEMOGRAPHICS;


select *
from raw_household_demographics;

CREATE OR REPLACE TABLE RAW_CUSTOMER_DEMOGRAPHICS AS
SELECT
    *,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    'CUSTOMER_ADDRESS_SOURCE' AS SOURCE_FILE_NAME,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_DEMOGRAPHICS;

select * 
from raw_customer_demographics;


select *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.WEB_SALES
LIMIT 100;

-- count how many web_sales come from our 100k customers, 11 mill in total
SELECT COUNT(*)
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.WEB_SALES ws
WHERE ws.WS_BILL_CUSTOMER_SK IN (
    SELECT C_CUSTOMER_SK
    FROM RAW.RAW_CUSTOMER
);

-- create web sales table
CREATE OR REPLACE TABLE RAW.WEB_SALES AS
SELECT
    ws.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.WEB_SALES ws
WHERE ws.WS_BILL_CUSTOMER_SK IN (
    SELECT C_CUSTOMER_SK
    FROM RAW.RAW_CUSTOMER
);


CREATE OR REPLACE TABLE RAW.STORE_SALES AS
SELECT
    ss.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES ss
WHERE ss.SS_CUSTOMER_SK IN (
    SELECT C_CUSTOMER_SK
    FROM RAW.RAW_CUSTOMER
);


-- Count how many rows are in store sales, there's 42 million 
SELECT COUNT(*)
FROM RAW.STORE_SALES;

CREATE OR REPLACE TABLE RAW.CATALOG_SALES AS
SELECT
    cs.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CATALOG_SALES cs
WHERE cs.CS_BILL_CUSTOMER_SK IN (
    SELECT C_CUSTOMER_SK
    FROM RAW.RAW_CUSTOMER
);


-- 22 million rows
SELECT COUNT(*)
FROM RAW.CATALOG_SALES;

select *
From store_sales
Limit 10;

select *
from catalog_sales
Limit 10;


-- Return tables
show tables;

CREATE OR REPLACE TABLE RAW.WEB_RETURNS AS
SELECT
    wr.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.WEB_RETURNS wr
WHERE wr.WR_RETURNING_CUSTOMER_SK IN (
    SELECT C_CUSTOMER_SK
    FROM RAW.RAW_CUSTOMER
);

CREATE OR REPLACE TABLE RAW.CATALOG_RETURNS AS
SELECT
    cr.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CATALOG_RETURNS cr
WHERE cr.CR_RETURNING_CUSTOMER_SK IN (
    SELECT C_CUSTOMER_SK
    FROM RAW.RAW_CUSTOMER
);


CREATE OR REPLACE TABLE RAW.STORE_RETURNS AS
SELECT
    sr.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_RETURNS sr
WHERE sr.SR_CUSTOMER_SK IN (
    SELECT C_CUSTOMER_SK
    FROM RAW.RAW_CUSTOMER
);

-- 1 mill web returns
SELECT COUNT(*) FROM RAW.WEB_RETURNS;

-- 4 mill store returns 
SELECT COUNT(*) FROM RAW.STORE_RETURNS;

-- And 2 mill catalog returns
SELECT COUNT(*) FROM RAW.CATALOG_RETURNS;

-- Now onto the marketing domain

CREATE OR REPLACE TABLE RAW.WEB_SITE AS
SELECT
    wsite.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.WEB_SITE wsite;

CREATE OR REPLACE TABLE RAW.WEB_PAGE AS
SELECT
    wp.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.WEB_PAGE wp
WHERE wp.WP_WEB_PAGE_SK IS NOT NULL;

-- product domain

CREATE OR REPLACE TABLE RAW.PROMOTION AS
SELECT
    p.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.PROMOTION p
WHERE p.P_PROMO_SK IS NOT NULL;


select *
from SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.WAREHOUSE;


CREATE OR REPLACE TABLE RAW.WAREHOUSE AS
SELECT
    w.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.WAREHOUSE w
WHERE w.W_WAREHOUSE_SK IS NOT NULL;

-- I will not be adding the inventory table because it's very big and I won't be utlising it for much

show tables;

CREATE OR REPLACE TABLE RAW.Store AS
SELECT
    sto.*,
    UUID_STRING() AS LOAD_ID,
    CURRENT_TIMESTAMP() AS LOAD_DATE,
    '2026W01' AS BATCH_ID
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.store sto
WHERE sto.S_STORE_SK IS NOT NULL;

show tables;

select *
from date_dim
limit 100;

select *
from store;

show tables;

