CREATE OR REPLACE TABLE RAW_CUSTOMER (
    C_CUSTOMER_SK NUMBER,
    C_CUSTOMER_ID STRING,
    C_CURRENT_CDEMO_SK NUMBER,
    C_CURRENT_HDEMO_SK NUMBER,
    C_CURRENT_ADDR_SK NUMBER,
    C_FIRST_SHIPTO_DATE_SK NUMBER,
    C_FIRST_SALES_DATE_SK NUMBER,
    C_SALUTATION STRING,
    C_FIRST_NAME STRING,
    C_LAST_NAME STRING,
    C_PREFERRED_CUST_FLAG STRING,
    C_BIRTH_DAY NUMBER,
    C_BIRTH_MONTH NUMBER,
    C_BIRTH_YEAR NUMBER,
    C_BIRTH_COUNTRY STRING,
    C_LOGIN STRING,
    C_EMAIL_ADDRESS STRING,
    C_LAST_REVIEW_DATE DATE,

    LOAD_ID STRING,
    LOAD_DATE TIMESTAMP,
    SOURCE_FILE_NAME STRING,
    BATCH_ID STRING
);

SET LOAD_ID = UUID_STRING();
SET BATCH_ID = '2026W01';




DESC TABLE CUSTOMER;
FILE_FORMAT = (FORMAT_NAME = STAGE.CSV_FORMAT);

SELECT COUNT(*)
FROM RAW_CUSTOMER;

describe table customer;

SELECT *
FROM @STAGE.CUSTOMER_STAGE
(FILE_FORMAT => STAGE.CSV_FORMAT);


INSERT INTO RAW_CUSTOMER
SELECT
    *,
    UUID_STRING(),
    CURRENT_TIMESTAMP(),
    'CUSTOMER_SOURCE',
    '2026W01'
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER
LIMIT 10000;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(C_CUSTOMER_SK IS NULL) AS NULL_CUSTOMER_SK,
    COUNT_IF(C_CUSTOMER_ID IS NULL) AS NULL_CUSTOMER_ID,
    COUNT_IF(C_CURRENT_CDEMO_SK IS NULL) AS NULL_CDEMO_SK,
    COUNT_IF(C_CURRENT_HDEMO_SK IS NULL) AS NULL_HDEMO_SK,
    COUNT_IF(C_CURRENT_ADDR_SK IS NULL) AS NULL_ADDR_SK,
    COUNT_IF(C_FIRST_NAME IS NULL) AS NULL_FIRST_NAME,
    COUNT_IF(C_LAST_NAME IS NULL) AS NULL_LAST_NAME,
    COUNT_IF(C_EMAIL_ADDRESS IS NULL) AS NULL_EMAIL
FROM RAW_CUSTOMER;

select *
from raw_customer;

show tables;

CREATE OR REPLACE TABLE RAW.WEB_SALES AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.WEB_SALES;

