-- For marketing domain and product domain curated

-- marketing domain curated
CREATE OR REPLACE TABLE CURATED.PROMOTION AS

WITH deduped AS (
    SELECT *
    FROM RAW.PROMOTION
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY P_PROMO_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    CAST(P_PROMO_SK AS NUMBER)          AS PROMO_SK,
    P_PROMO_ID                          AS PROMO_ID,

    CAST(P_START_DATE_SK AS NUMBER)     AS START_DATE_SK,
    CAST(P_END_DATE_SK AS NUMBER)       AS END_DATE_SK,
    CAST(P_ITEM_SK AS NUMBER)           AS ITEM_SK,

    ROUND(COALESCE(P_COST,0),2)         AS COST,
    COALESCE(P_RESPONSE_TARGET,0)       AS RESPONSE_TARGET,

    TRIM(P_PROMO_NAME)                  AS PROMO_NAME,

    COALESCE(P_CHANNEL_DMAIL,'N')       AS CHANNEL_DMAIL,
    COALESCE(P_CHANNEL_EMAIL,'N')       AS CHANNEL_EMAIL,
    COALESCE(P_CHANNEL_CATALOG,'N')     AS CHANNEL_CATALOG,
    COALESCE(P_CHANNEL_TV,'N')          AS CHANNEL_TV,
    COALESCE(P_CHANNEL_RADIO,'N')       AS CHANNEL_RADIO,
    COALESCE(P_CHANNEL_PRESS,'N')       AS CHANNEL_PRESS,
    COALESCE(P_CHANNEL_EVENT,'N')       AS CHANNEL_EVENT,
    COALESCE(P_CHANNEL_DEMO,'N')        AS CHANNEL_DEMO,

    TRIM(P_CHANNEL_DETAILS)             AS CHANNEL_DETAILS,
    TRIM(P_PURPOSE)                     AS PURPOSE,

    COALESCE(P_DISCOUNT_ACTIVE,'N')     AS DISCOUNT_ACTIVE,

    LOAD_ID,
    LOAD_DATE,
    BATCH_ID

FROM deduped

WHERE COALESCE(P_PROMO_SK,0) > 0;

select *
from promotion;

CREATE OR REPLACE TABLE CURATED.WEB_PAGE AS

WITH deduped AS (
    SELECT *
    FROM RAW.WEB_PAGE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY WP_WEB_PAGE_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    CAST(WP_WEB_PAGE_SK AS NUMBER)        AS WEB_PAGE_SK,
    WP_WEB_PAGE_ID                        AS WEB_PAGE_ID,

    CAST(WP_CREATION_DATE_SK AS NUMBER)   AS CREATION_DATE_SK,
    CAST(WP_ACCESS_DATE_SK AS NUMBER)     AS ACCESS_DATE_SK,

    TRY_TO_DATE(WP_REC_START_DATE)        AS REC_START_DATE,
    TRY_TO_DATE(WP_REC_END_DATE)          AS REC_END_DATE,

    COALESCE(WP_AUTOGEN_FLAG,'N')         AS AUTOGEN_FLAG,

    CAST(WP_CUSTOMER_SK AS NUMBER)        AS CUSTOMER_SK,

    LOWER(TRIM(WP_URL))                   AS URL,
    LOWER(TRIM(WP_TYPE))                  AS PAGE_TYPE,

    COALESCE(WP_CHAR_COUNT,0)             AS CHAR_COUNT,
    COALESCE(WP_LINK_COUNT,0)             AS LINK_COUNT,
    COALESCE(WP_IMAGE_COUNT,0)            AS IMAGE_COUNT,
    COALESCE(WP_MAX_AD_COUNT,0)           AS MAX_AD_COUNT,

    LOAD_ID,
    LOAD_DATE,
    BATCH_ID

FROM deduped

WHERE COALESCE(WP_WEB_PAGE_SK,0) > 0
  AND COALESCE(WP_CHAR_COUNT,0) >= 0
  AND COALESCE(WP_LINK_COUNT,0) >= 0
  AND COALESCE(WP_IMAGE_COUNT,0) >= 0;

select *
from promotion;

CREATE OR REPLACE TABLE CURATED.WEB_SITE AS

WITH deduped AS (
    SELECT *
    FROM RAW.WEB_SITE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY WEB_SITE_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    CAST(WEB_SITE_SK AS NUMBER)         AS WEB_SITE_SK,
    WEB_SITE_ID                         AS WEB_SITE_ID,

    TRY_TO_DATE(WEB_REC_START_DATE)     AS REC_START_DATE,
    TRY_TO_DATE(WEB_REC_END_DATE)       AS REC_END_DATE,

    CAST(WEB_OPEN_DATE_SK AS NUMBER)    AS OPEN_DATE_SK,
    CAST(WEB_CLOSE_DATE_SK AS NUMBER)   AS CLOSE_DATE_SK,

    TRIM(WEB_NAME)                      AS WEB_NAME,
    TRIM(WEB_CLASS)                     AS WEB_CLASS,
    TRIM(WEB_MANAGER)                   AS WEB_MANAGER,

    COALESCE(WEB_MKT_ID,0)              AS WEB_MKT_ID,
    TRIM(WEB_MKT_CLASS)                 AS WEB_MKT_CLASS,
    TRIM(WEB_MKT_DESC)                  AS WEB_MKT_DESC,
    TRIM(WEB_MARKET_MANAGER)            AS WEB_MARKET_MANAGER,

    COALESCE(WEB_COMPANY_ID,0)          AS COMPANY_ID,
    TRIM(WEB_COMPANY_NAME)              AS COMPANY_NAME,

    TRIM(WEB_STREET_NUMBER)             AS STREET_NUMBER,
    TRIM(WEB_STREET_NAME)               AS STREET_NAME,
    TRIM(WEB_STREET_TYPE)               AS STREET_TYPE,
    TRIM(WEB_SUITE_NUMBER)              AS SUITE_NUMBER,

    INITCAP(TRIM(WEB_CITY))             AS CITY,
    INITCAP(TRIM(WEB_COUNTY))           AS COUNTY,
    UPPER(TRIM(WEB_STATE))              AS STATE,
    TRIM(WEB_ZIP)                       AS ZIP,
    INITCAP(TRIM(WEB_COUNTRY))          AS COUNTRY,

    ROUND(COALESCE(WEB_GMT_OFFSET,0),2)     AS GMT_OFFSET,
    ROUND(COALESCE(WEB_TAX_PERCENTAGE,0),2) AS TAX_PERCENTAGE,

    LOAD_ID,
    LOAD_DATE,
    BATCH_ID

FROM deduped

WHERE COALESCE(WEB_SITE_SK,0) > 0;

-- product domain curated

--item

CREATE OR REPLACE TABLE CURATED.ITEM AS

WITH deduped AS (
    SELECT *
    FROM RAW.ITEM
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY I_ITEM_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    /* Keys */
    CAST(I_ITEM_SK AS NUMBER)            AS ITEM_SK,
    I_ITEM_ID                            AS ITEM_ID,

    /* Dates */
    TRY_TO_DATE(I_REC_START_DATE)        AS REC_START_DATE,
    TRY_TO_DATE(I_REC_END_DATE)          AS REC_END_DATE,

    /* Item Details */
    TRIM(I_ITEM_DESC)                    AS ITEM_DESC,

    ROUND(COALESCE(I_CURRENT_PRICE,0),2)   AS CURRENT_PRICE,
    ROUND(COALESCE(I_WHOLESALE_COST,0),2)  AS WHOLESALE_COST,

    CAST(I_BRAND_ID AS NUMBER)           AS BRAND_ID,
    TRIM(I_BRAND)                        AS BRAND,

    CAST(I_CLASS_ID AS NUMBER)           AS CLASS_ID,
    TRIM(I_CLASS)                        AS CLASS,

    CAST(I_CATEGORY_ID AS NUMBER)        AS CATEGORY_ID,
    TRIM(I_CATEGORY)                     AS CATEGORY,

    CAST(I_MANUFACT_ID AS NUMBER)        AS MANUFACT_ID,
    TRIM(I_MANUFACT)                     AS MANUFACT,

    NULLIF(TRIM(I_SIZE),'N/A')           AS SIZE,
    NULLIF(TRIM(I_FORMULATION),'N/A')    AS FORMULATION,
    NULLIF(TRIM(I_COLOR),'N/A')          AS COLOR,
    NULLIF(TRIM(I_UNITS),'N/A')          AS UNITS,
    NULLIF(TRIM(I_CONTAINER),'Unknown')  AS CONTAINER,

    CAST(COALESCE(I_MANAGER_ID,0) AS NUMBER) AS MANAGER_ID,

    TRIM(I_PRODUCT_NAME)                 AS PRODUCT_NAME,

    LOAD_ID,
    LOAD_DATE,
    BATCH_ID

FROM deduped

WHERE COALESCE(I_ITEM_SK,0) > 0
  AND COALESCE(I_CURRENT_PRICE,0) >= 0
  AND COALESCE(I_WHOLESALE_COST,0) >= 0;

--warehouse

CREATE OR REPLACE TABLE CURATED.WAREHOUSE AS

WITH deduped AS (
    SELECT *
    FROM RAW.WAREHOUSE
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY W_WAREHOUSE_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    /* Keys */
    CAST(W_WAREHOUSE_SK AS NUMBER)      AS WAREHOUSE_SK,
    W_WAREHOUSE_ID                      AS WAREHOUSE_ID,

    /* Warehouse Details */
    TRIM(W_WAREHOUSE_NAME)              AS WAREHOUSE_NAME,

    COALESCE(W_WAREHOUSE_SQ_FT,0)       AS WAREHOUSE_SQ_FT,

    /* Address */
    TRIM(W_STREET_NUMBER)               AS STREET_NUMBER,
    TRIM(W_STREET_NAME)                 AS STREET_NAME,
    TRIM(W_STREET_TYPE)                 AS STREET_TYPE,
    TRIM(W_SUITE_NUMBER)                AS SUITE_NUMBER,

    INITCAP(TRIM(W_CITY))               AS CITY,
    INITCAP(TRIM(W_COUNTY))             AS COUNTY,
    UPPER(TRIM(W_STATE))                AS STATE,
    TRIM(W_ZIP)                         AS ZIP,
    INITCAP(TRIM(W_COUNTRY))            AS COUNTRY,

    ROUND(COALESCE(W_GMT_OFFSET,0),2)   AS GMT_OFFSET,

    LOAD_ID,
    LOAD_DATE,
    BATCH_ID

FROM deduped

WHERE COALESCE(W_WAREHOUSE_SK,0) > 0
  AND COALESCE(W_WAREHOUSE_SQ_FT,0) >= 0;