CREATE OR REPLACE TABLE CURATED.WEB_RETURNS AS

WITH DEDUPED AS (
    SELECT *
    FROM RAW.WEB_RETURNS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY WR_ORDER_NUMBER, WR_ITEM_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    /* Keys */
    WR_RETURNED_DATE_SK,
    WR_RETURNED_TIME_SK,

    WR_ITEM_SK,

    WR_REFUNDED_CUSTOMER_SK,
    WR_REFUNDED_CDEMO_SK,
    WR_REFUNDED_HDEMO_SK,
    WR_REFUNDED_ADDR_SK,

    WR_RETURNING_CUSTOMER_SK,
    WR_RETURNING_CDEMO_SK,
    WR_RETURNING_HDEMO_SK,
    WR_RETURNING_ADDR_SK,

    WR_WEB_PAGE_SK,
    WR_REASON_SK,

    /* Transaction */
    WR_ORDER_NUMBER,

    /* Measures */
    COALESCE(WR_RETURN_QUANTITY,0) AS RETURN_QUANTITY,

    ROUND(COALESCE(WR_RETURN_AMT,0),2) AS RETURN_AMT,
    ROUND(COALESCE(WR_RETURN_TAX,0),2) AS RETURN_TAX,
    ROUND(COALESCE(WR_RETURN_AMT_INC_TAX,0),2) AS RETURN_AMT_INC_TAX,
    ROUND(COALESCE(WR_FEE,0),2) AS FEE,
    ROUND(COALESCE(WR_RETURN_SHIP_COST,0),2) AS RETURN_SHIP_COST,

    ROUND(COALESCE(WR_REFUNDED_CASH,0),2) AS REFUNDED_CASH,
    ROUND(COALESCE(WR_REVERSED_CHARGE,0),2) AS REVERSED_CHARGE,
    ROUND(COALESCE(WR_ACCOUNT_CREDIT,0),2) AS ACCOUNT_CREDIT,
    ROUND(COALESCE(WR_NET_LOSS,0),2) AS NET_LOSS,

    CASE
        WHEN COALESCE(WR_RETURN_AMT,0) >= 1000 THEN 'High Value Return'
        WHEN COALESCE(WR_RETURN_AMT,0) >= 100 THEN 'Medium Value Return'
        ELSE 'Low Value Return'
    END AS RETURN_BRACKET,

    DEDUPED.LOAD_ID,
    DEDUPED.LOAD_DATE,
    DEDUPED.BATCH_ID

FROM DEDUPED

INNER JOIN CURATED.CUSTOMER c
    ON DEDUPED.WR_REFUNDED_CUSTOMER_SK = c.C_CUSTOMER_SK

WHERE COALESCE(WR_RETURN_QUANTITY,0) > 0;

CREATE OR REPLACE TABLE CURATED.CATALOG_RETURNS AS

WITH DEDUPED AS (
    SELECT *
    FROM RAW.CATALOG_RETURNS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CR_ORDER_NUMBER, CR_ITEM_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    /* Keys */
    CR_RETURNED_DATE_SK,
    CR_RETURNED_TIME_SK,
    CR_ITEM_SK,

    CR_REFUNDED_CUSTOMER_SK,
    CR_REFUNDED_CDEMO_SK,
    CR_REFUNDED_HDEMO_SK,
    CR_REFUNDED_ADDR_SK,

    CR_RETURNING_CUSTOMER_SK,
    CR_RETURNING_CDEMO_SK,
    CR_RETURNING_HDEMO_SK,
    CR_RETURNING_ADDR_SK,

    CR_CALL_CENTER_SK,
    CR_CATALOG_PAGE_SK,
    CR_SHIP_MODE_SK,
    CR_WAREHOUSE_SK,
    CR_REASON_SK,

    /* Transaction */
    CR_ORDER_NUMBER,

    /* Measures */
    COALESCE(CR_RETURN_QUANTITY,0) AS RETURN_QUANTITY,

    ROUND(COALESCE(CR_RETURN_AMOUNT,0),2) AS RETURN_AMOUNT,
    ROUND(COALESCE(CR_RETURN_TAX,0),2) AS RETURN_TAX,
    ROUND(COALESCE(CR_RETURN_AMT_INC_TAX,0),2) AS RETURN_AMT_INC_TAX,
    ROUND(COALESCE(CR_FEE,0),2) AS FEE,
    ROUND(COALESCE(CR_RETURN_SHIP_COST,0),2) AS RETURN_SHIP_COST,

    ROUND(COALESCE(CR_REFUNDED_CASH,0),2) AS REFUNDED_CASH,
    ROUND(COALESCE(CR_REVERSED_CHARGE,0),2) AS REVERSED_CHARGE,
    ROUND(COALESCE(CR_STORE_CREDIT,0),2) AS STORE_CREDIT,
    ROUND(COALESCE(CR_NET_LOSS,0),2) AS NET_LOSS,

    CASE
        WHEN COALESCE(CR_RETURN_AMOUNT,0) >= 1000 THEN 'High Value Return'
        WHEN COALESCE(CR_RETURN_AMOUNT,0) >= 100 THEN 'Medium Value Return'
        ELSE 'Low Value Return'
    END AS RETURN_BRACKET,

    DEDUPED.LOAD_ID,
    DEDUPED.LOAD_DATE,
    DEDUPED.BATCH_ID

FROM DEDUPED

INNER JOIN CURATED.CUSTOMER c
    ON DEDUPED.CR_REFUNDED_CUSTOMER_SK = c.C_CUSTOMER_SK

WHERE COALESCE(CR_RETURN_QUANTITY,0) > 0;

CREATE OR REPLACE TABLE CURATED.STORE_RETURNS AS

WITH DEDUPED AS (
    SELECT *
    FROM RAW.STORE_RETURNS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY SR_TICKET_NUMBER, SR_ITEM_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    /* Keys */
    SR_RETURNED_DATE_SK,
    SR_RETURN_TIME_SK,
    SR_ITEM_SK,

    SR_CUSTOMER_SK,
    SR_CDEMO_SK,
    SR_HDEMO_SK,
    SR_ADDR_SK,

    SR_STORE_SK,
    SR_REASON_SK,

    /* Transaction */
    SR_TICKET_NUMBER,

    /* Measures */
    COALESCE(SR_RETURN_QUANTITY,0) AS RETURN_QUANTITY,

    ROUND(COALESCE(SR_RETURN_AMT,0),2) AS RETURN_AMT,
    ROUND(COALESCE(SR_RETURN_TAX,0),2) AS RETURN_TAX,
    ROUND(COALESCE(SR_RETURN_AMT_INC_TAX,0),2) AS RETURN_AMT_INC_TAX,
    ROUND(COALESCE(SR_FEE,0),2) AS FEE,
    ROUND(COALESCE(SR_RETURN_SHIP_COST,0),2) AS RETURN_SHIP_COST,

    ROUND(COALESCE(SR_REFUNDED_CASH,0),2) AS REFUNDED_CASH,
    ROUND(COALESCE(SR_REVERSED_CHARGE,0),2) AS REVERSED_CHARGE,
    ROUND(COALESCE(SR_STORE_CREDIT,0),2) AS STORE_CREDIT,
    ROUND(COALESCE(SR_NET_LOSS,0),2) AS NET_LOSS,

    CASE
        WHEN COALESCE(SR_RETURN_AMT,0) >= 1000 THEN 'High Value Return'
        WHEN COALESCE(SR_RETURN_AMT,0) >= 100 THEN 'Medium Value Return'
        ELSE 'Low Value Return'
    END AS RETURN_BRACKET,

    DEDUPED.LOAD_ID,
    DEDUPED.LOAD_DATE,
    DEDUPED.BATCH_ID

FROM DEDUPED

INNER JOIN CURATED.CUSTOMER c
    ON DEDUPED.SR_CUSTOMER_SK = c.C_CUSTOMER_SK

WHERE COALESCE(SR_RETURN_QUANTITY,0) > 0;