-- Create curated layer tables with cleansing, deduplication, and standardisation

CREATE OR REPLACE TABLE CURATED.CUSTOMER AS
SELECT
    TRY_TO_NUMBER(C_CUSTOMER_SK)           AS C_CUSTOMER_SK,
    C_CUSTOMER_ID                          AS C_CUSTOMER_ID,
    TRY_TO_NUMBER(C_CURRENT_CDEMO_SK)      AS C_CURRENT_CDEMO_SK,
    TRY_TO_NUMBER(C_CURRENT_HDEMO_SK)      AS C_CURRENT_HDEMO_SK,
    TRY_TO_NUMBER(C_CURRENT_ADDR_SK)       AS C_CURRENT_ADDR_SK,
    TRY_TO_NUMBER(C_FIRST_SHIPTO_DATE_SK)  AS C_FIRST_SHIPTO_DATE_SK,
    TRY_TO_NUMBER(C_FIRST_SALES_DATE_SK)   AS C_FIRST_SALES_DATE_SK,

    TRIM(C_SALUTATION)                     AS C_SALUTATION,
    TRIM(C_FIRST_NAME)                     AS C_FIRST_NAME,
    TRIM(C_LAST_NAME)                      AS C_LAST_NAME,

    UPPER(TRIM(C_PREFERRED_CUST_FLAG))     AS C_PREFERRED_CUST_FLAG,

    TRY_TO_NUMBER(C_BIRTH_DAY)             AS C_BIRTH_DAY,
    TRY_TO_NUMBER(C_BIRTH_MONTH)           AS C_BIRTH_MONTH,
    TRY_TO_NUMBER(C_BIRTH_YEAR)            AS C_BIRTH_YEAR,

    INITCAP(TRIM(C_BIRTH_COUNTRY))         AS C_BIRTH_COUNTRY,

    LOWER(TRIM(C_LOGIN))                   AS C_LOGIN,
    LOWER(TRIM(C_EMAIL_ADDRESS))           AS C_EMAIL_ADDRESS,

    TRY_TO_DATE(C_LAST_REVIEW_DATE)        AS C_LAST_REVIEW_DATE,

    LOAD_ID,
    LOAD_DATE,
    SOURCE_FILE_NAME,
    BATCH_ID

FROM RAW.RAW_CUSTOMER;


select * 
from customer;

SELECT
COUNT(*) AS TOTAL_ROWS,
COUNT(DISTINCT C_CUSTOMER_SK) AS DISTINCT_CUSTOMERS
FROM 


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT C_CUSTOMER_SK) AS DISTINCT_CUSTOMERS
FROM RAW_CUSTOMER;

TRUNCATE TABLE RAW_CUSTOMER;

select * 
from customer;

-- invalid customers
CREATE OR REPLACE TABLE CURATED.INVALID_CUSTOMER AS
SELECT *
FROM CURATED.CUSTOMER
WHERE
      C_FIRST_NAME IS NULL
   OR TRIM(C_FIRST_NAME) = ''
   OR C_LAST_NAME IS NULL
   OR TRIM(C_LAST_NAME) = ''
   OR C_EMAIL_ADDRESS IS NULL
   OR TRIM(C_EMAIL_ADDRESS) = ''
   OR C_EMAIL_ADDRESS = 'unknown@example.com'
   OR C_CURRENT_ADDR_SK IS NULL;

select count(*)
from invalid_customer;

CREATE OR REPLACE TABLE CURATED.CUSTOMER AS

SELECT *
FROM (

    SELECT

        /* Numeric conversions */
        TRY_TO_NUMBER(C_CUSTOMER_SK)          AS C_CUSTOMER_SK,
        TRIM(C_CUSTOMER_ID)                   AS C_CUSTOMER_ID,
        TRY_TO_NUMBER(C_CURRENT_CDEMO_SK)     AS C_CURRENT_CDEMO_SK,
        TRY_TO_NUMBER(C_CURRENT_HDEMO_SK)     AS C_CURRENT_HDEMO_SK,
        TRY_TO_NUMBER(C_CURRENT_ADDR_SK)      AS C_CURRENT_ADDR_SK,
        TRY_TO_NUMBER(C_FIRST_SHIPTO_DATE_SK) AS C_FIRST_SHIPTO_DATE_SK,
        TRY_TO_NUMBER(C_FIRST_SALES_DATE_SK)  AS C_FIRST_SALES_DATE_SK,

        /* Trim whitespace and standardise text */
        INITCAP(TRIM(C_SALUTATION))           AS C_SALUTATION,
        INITCAP(TRIM(C_FIRST_NAME))           AS C_FIRST_NAME,
        INITCAP(TRIM(C_LAST_NAME))            AS C_LAST_NAME,

        UPPER(TRIM(
            COALESCE(C_PREFERRED_CUST_FLAG,'N')
        )) AS C_PREFERRED_CUST_FLAG,

        /* Numeric birth attributes */
        TRY_TO_NUMBER(C_BIRTH_DAY)            AS C_BIRTH_DAY,
        TRY_TO_NUMBER(C_BIRTH_MONTH)          AS C_BIRTH_MONTH,
        TRY_TO_NUMBER(C_BIRTH_YEAR)           AS C_BIRTH_YEAR,

        INITCAP(TRIM(
            COALESCE(C_BIRTH_COUNTRY,'Unknown')
        )) AS C_BIRTH_COUNTRY,

        LOWER(TRIM(
            COALESCE(C_LOGIN,'unknown')
        )) AS C_LOGIN,

        LOWER(TRIM(
            COALESCE(C_EMAIL_ADDRESS,'unknown@example.com')
        )) AS C_EMAIL_ADDRESS,

        /* Date conversion */
        TRY_TO_DATE(C_LAST_REVIEW_DATE)       AS C_LAST_REVIEW_DATE,

        /* Derived business attributes */
        YEAR(CURRENT_DATE())
          - TRY_TO_NUMBER(C_BIRTH_YEAR)
          AS CUSTOMER_AGE,

        CASE
            WHEN TRY_TO_NUMBER(C_BIRTH_YEAR) IS NULL
                THEN 'Unknown'
            WHEN YEAR(CURRENT_DATE())
                 - TRY_TO_NUMBER(C_BIRTH_YEAR) < 25
                THEN 'Young Adult'
            WHEN YEAR(CURRENT_DATE())
                 - TRY_TO_NUMBER(C_BIRTH_YEAR) < 45
                THEN 'Adult'
            WHEN YEAR(CURRENT_DATE())
                 - TRY_TO_NUMBER(C_BIRTH_YEAR) < 65
                THEN 'Middle Aged'
            ELSE 'Senior'
        END AS AGE_GROUP,

        /* Audit metadata retained */
        LOAD_ID,
        LOAD_DATE,
        SOURCE_FILE_NAME,
        BATCH_ID,

        /* Duplicate detection */
        ROW_NUMBER() OVER (
            PARTITION BY C_CUSTOMER_ID
            ORDER BY LOAD_DATE DESC
        ) AS RN

    FROM RAW.RAW_CUSTOMER
)
WHERE C_CUSTOMER_ID NOT IN (
SELECT C_CUSTOMER_ID
FROM CURATED.INVALID_CUSTOMER
);


QUALIFY RN = 1;

select *
from customer;

describe table customer;



select *
from raw_customer_demographics;

select *
from curated.customer;

describe table raw_customer_address;

-- Clean address

CREATE OR REPLACE TABLE CURATED.CUSTOMER_ADDRESS AS
WITH DEDUPED AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY CA_ADDRESS_SK
               ORDER BY LOAD_DATE DESC
           ) AS RN
    FROM RAW.raw_customer_address
)
SELECT
    CA_ADDRESS_SK,
    TRIM(CA_ADDRESS_ID) AS CA_ADDRESS_ID,

    -- add unknowns
    COALESCE(TRIM(CA_STREET_NUMBER), 'UNKNOWN') AS CA_STREET_NUMBER,
    UPPER(COALESCE(TRIM(CA_STREET_NAME), 'UNKNOWN')) AS CA_STREET_NAME,
    UPPER(COALESCE(TRIM(CA_STREET_TYPE), 'UNKNOWN')) AS CA_STREET_TYPE,
    COALESCE(TRIM(CA_SUITE_NUMBER), 'N/A') AS CA_SUITE_NUMBER,

    UPPER(COALESCE(TRIM(CA_CITY), 'UNKNOWN')) AS CA_CITY,
    UPPER(COALESCE(TRIM(CA_COUNTY), 'UNKNOWN')) AS CA_COUNTY,
    UPPER(COALESCE(TRIM(CA_STATE), 'UNKNOWN')) AS CA_STATE,
    TRIM(COALESCE(CA_ZIP, 'UNKNOWN')) AS CA_ZIP,
    UPPER(COALESCE(TRIM(CA_COUNTRY), 'UNKNOWN')) AS CA_COUNTRY,

    COALESCE(CA_GMT_OFFSET, 0) AS CA_GMT_OFFSET,

    UPPER(COALESCE(TRIM(CA_LOCATION_TYPE), 'UNKNOWN')) AS CA_LOCATION_TYPE,

   -- make regions
    CASE
        WHEN UPPER(CA_STATE) IN ('CA','OR','WA','AK','HI')
            THEN 'WEST'
        WHEN UPPER(CA_STATE) IN ('NY','NJ','MA','CT','RI','VT','NH','ME','PA')
            THEN 'EAST'
        WHEN UPPER(CA_STATE) IN ('TX','OK','FL','GA','AL','MS','LA','SC','NC','TN','KY','VA','WV','AR')
            THEN 'SOUTH'
        WHEN UPPER(CA_STATE) IN ('IL','IN','IA','KS','MI','MN','MO','NE','ND','OH','SD','WI')
            THEN 'MIDWEST'
        ELSE 'OTHER'
    END AS REGION,

    LOAD_ID,
    LOAD_DATE,
    SOURCE_FILE_NAME,
    BATCH_ID

FROM DEDUPED
WHERE RN = 1
  AND CA_ADDRESS_SK IS NOT NULL;


--create curated customer demographic


select * 
from raw_customer_demographics;

describe table raw_customer_demographics;


-- CURATED.CUSTOMER_DEMOGRAPHICS
-- Purpose: Cleanse and standardise customer demographics

CREATE OR REPLACE TABLE CURATED.CUSTOMER_DEMOGRAPHICS AS

WITH DEDUPED AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY CD_DEMO_SK
               ORDER BY LOAD_DATE DESC
           ) AS RN
    FROM raw_customer_demographics
)

SELECT

    -- Primary Key
    CD_DEMO_SK,

    -- Gender
    CASE
        WHEN UPPER(TRIM(CD_GENDER)) = 'M' THEN 'MALE'
        WHEN UPPER(TRIM(CD_GENDER)) = 'F' THEN 'FEMALE'
        ELSE 'UNKNOWN'
    END AS CD_GENDER,

    -- Marital Status
    CASE
        WHEN UPPER(TRIM(CD_MARITAL_STATUS)) = 'M' THEN 'MARRIED'
        WHEN UPPER(TRIM(CD_MARITAL_STATUS)) = 'S' THEN 'SINGLE'
        WHEN UPPER(TRIM(CD_MARITAL_STATUS)) = 'D' THEN 'DIVORCED'
        WHEN UPPER(TRIM(CD_MARITAL_STATUS)) = 'W' THEN 'WIDOWED'
        ELSE 'UNKNOWN'
    END AS CD_MARITAL_STATUS,

    -- Education
    UPPER(COALESCE(TRIM(CD_EDUCATION_STATUS), 'UNKNOWN'))
        AS CD_EDUCATION_STATUS,

    -- Purchase Estimate
    COALESCE(CD_PURCHASE_ESTIMATE, 0)
        AS CD_PURCHASE_ESTIMATE,

    -- Credit Rating
    UPPER(COALESCE(TRIM(CD_CREDIT_RATING), 'UNKNOWN'))
        AS CD_CREDIT_RATING,

    -- Dependents
    COALESCE(CD_DEP_COUNT, 0)
        AS CD_DEP_COUNT,

    COALESCE(CD_DEP_EMPLOYED_COUNT, 0)
        AS CD_DEP_EMPLOYED_COUNT,

    COALESCE(CD_DEP_COLLEGE_COUNT, 0)
        AS CD_DEP_COLLEGE_COUNT,


    -- Metadata
    LOAD_ID,
    LOAD_DATE,
    SOURCE_FILE_NAME,
    BATCH_ID

FROM DEDUPED
WHERE RN = 1
  AND CD_DEMO_SK IS NOT NULL;

describe table raw_household_demographics;

-- curated household demographics table

-- CURATED.HOUSEHOLD_DEMOGRAPHICS
-- Purpose: Cleanse and standardise household demographics
-- Layer: Curated


CREATE OR REPLACE TABLE CURATED.HOUSEHOLD_DEMOGRAPHICS AS

WITH DEDUPED AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY HD_DEMO_SK
               ORDER BY LOAD_DATE DESC
           ) AS RN
    FROM raw_household_demographics
)

SELECT

    -- Primary Key
    HD_DEMO_SK,

    -- Foreign Key
    HD_INCOME_BAND_SK,

    -- Household Attributes
    UPPER(COALESCE(TRIM(HD_BUY_POTENTIAL), 'UNKNOWN'))
        AS HD_BUY_POTENTIAL,

    COALESCE(HD_DEP_COUNT, 0)
        AS HD_DEP_COUNT,

    COALESCE(HD_VEHICLE_COUNT, 0)
        AS HD_VEHICLE_COUNT,

    -- Metadata
    LOAD_ID,
    LOAD_DATE,
    SOURCE_FILE_NAME,
    BATCH_ID

FROM DEDUPED
WHERE RN = 1
  AND HD_DEMO_SK IS NOT NULL;


describe table raw_income_band;

-- CURATED.INCOME_BAND
-- Purpose: Cleanse and standardise income band data
-- Layer: Curated

CREATE OR REPLACE TABLE CURATED.INCOME_BAND AS

WITH DEDUPED AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY IB_INCOME_BAND_SK
               ORDER BY LOAD_DATE DESC
           ) AS RN
    FROM raw_income_band
)

SELECT

    -- Primary Key
    IB_INCOME_BAND_SK,

    -- Income Range
    COALESCE(IB_LOWER_BOUND, 0) AS IB_LOWER_BOUND,
    COALESCE(IB_UPPER_BOUND, 0) AS IB_UPPER_BOUND,

    -- Metadata
    LOAD_ID,
    LOAD_DATE,
    SOURCE_FILE_NAME,
    BATCH_ID

FROM DEDUPED
WHERE RN = 1
  AND IB_INCOME_BAND_SK IS NOT NULL;

select * 
From RAW.WEB_SALES
Limit 10;

-- will add dates later with date_dim in modelled layer
SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM
WHERE D_DATE_SK = 2451831;


-- Create Curate WEB_SALES

CREATE OR REPLACE TABLE CURATED.WEB_SALES AS

WITH deduped AS (
    SELECT *
    FROM RAW.WEB_SALES
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY WS_ORDER_NUMBER, WS_ITEM_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    /* Keys */
    CAST(WS_SOLD_DATE_SK       AS NUMBER) AS SOLD_DATE_SK,
    CAST(WS_SOLD_TIME_SK       AS NUMBER) AS SOLD_TIME_SK,
    CAST(WS_SHIP_DATE_SK       AS NUMBER) AS SHIP_DATE_SK,
    CAST(WS_ITEM_SK            AS NUMBER) AS ITEM_SK,

    CAST(WS_BILL_CUSTOMER_SK   AS NUMBER) AS BILL_CUSTOMER_SK,
    CAST(WS_SHIP_CUSTOMER_SK   AS NUMBER) AS SHIP_CUSTOMER_SK,

    CAST(WS_BILL_ADDR_SK       AS NUMBER) AS BILL_ADDR_SK,
    CAST(WS_SHIP_ADDR_SK       AS NUMBER) AS SHIP_ADDR_SK,

    CAST(WS_WEB_PAGE_SK        AS NUMBER) AS WEB_PAGE_SK,
    CAST(WS_WEB_SITE_SK        AS NUMBER) AS WEB_SITE_SK,
    CAST(WS_SHIP_MODE_SK       AS NUMBER) AS SHIP_MODE_SK,
    CAST(WS_WAREHOUSE_SK       AS NUMBER) AS WAREHOUSE_SK,
    CAST(WS_PROMO_SK           AS NUMBER) AS PROMO_SK,

    /* Order Information */
    CAST(WS_ORDER_NUMBER AS NUMBER) AS ORDER_NUMBER,

    /* Measures */
    COALESCE(WS_QUANTITY, 0) AS QUANTITY,

    ROUND(COALESCE(WS_WHOLESALE_COST, 0), 2) AS WHOLESALE_COST,
    ROUND(COALESCE(WS_LIST_PRICE, 0), 2) AS LIST_PRICE,
    ROUND(COALESCE(WS_SALES_PRICE, 0), 2) AS SALES_PRICE,

    ROUND(COALESCE(WS_EXT_DISCOUNT_AMT, 0), 2) AS EXT_DISCOUNT_AMT,
    ROUND(COALESCE(WS_EXT_SALES_PRICE, 0), 2) AS EXT_SALES_PRICE,
    ROUND(COALESCE(WS_EXT_WHOLESALE_COST, 0), 2) AS EXT_WHOLESALE_COST,
    ROUND(COALESCE(WS_EXT_LIST_PRICE, 0), 2) AS EXT_LIST_PRICE,
    ROUND(COALESCE(WS_EXT_TAX, 0), 2) AS EXT_TAX,
    ROUND(COALESCE(WS_COUPON_AMT, 0), 2) AS COUPON_AMT,
    ROUND(COALESCE(WS_EXT_SHIP_COST, 0), 2) AS EXT_SHIP_COST,

    ROUND(COALESCE(WS_NET_PAID, 0), 2) AS NET_PAID,
    ROUND(COALESCE(WS_NET_PAID_INC_TAX, 0), 2) AS NET_PAID_INC_TAX,
    ROUND(COALESCE(WS_NET_PAID_INC_SHIP, 0), 2) AS NET_PAID_INC_SHIP,
    ROUND(COALESCE(WS_NET_PAID_INC_SHIP_TAX, 0), 2) AS NET_PAID_INC_SHIP_TAX,
    ROUND(COALESCE(WS_NET_PROFIT, 0), 2) AS NET_PROFIT,

    /* Derived Classifications */

    CASE
        WHEN WS_QUANTITY <= 10 THEN 'Small Order'
        WHEN WS_QUANTITY <= 50 THEN 'Medium Order'
        ELSE 'Large Order'
    END AS ORDER_SIZE_BAND,

    CASE
        WHEN WS_NET_PROFIT < 0 THEN 'Loss'
        WHEN WS_NET_PROFIT < 1000 THEN 'Low Profit'
        ELSE 'High Profit'
    END AS PROFIT_BAND,

    CASE
        WHEN WS_COUPON_AMT > 0 THEN 'Coupon Used'
        ELSE 'No Coupon'
    END AS COUPON_USAGE,

    CASE
        WHEN WS_EXT_DISCOUNT_AMT > 0 THEN 'Discounted'
        ELSE 'Full Price'
    END AS DISCOUNT_TYPE,

    d.LOAD_ID,
    d.LOAD_DATE,
    d.BATCH_ID

FROM deduped d

INNER JOIN CURATED.CUSTOMER c
ON d.WS_BILL_CUSTOMER_SK = c.C_CUSTOMER_SK

WHERE COALESCE(d.WS_QUANTITY, 0) > 0
  AND COALESCE(d.WS_LIST_PRICE, 0) >= 0
  AND COALESCE(d.WS_SALES_PRICE, 0) >= 0;



-- create curated store sales
CREATE OR REPLACE TABLE CURATED.STORE_SALES AS

WITH DEDUPED AS (
    SELECT *
    FROM RAW.STORE_SALES
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY SS_TICKET_NUMBER, SS_ITEM_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    /* Keys */
    SS_SOLD_DATE_SK,
    SS_SOLD_TIME_SK,
    SS_ITEM_SK,
    SS_CUSTOMER_SK,
    SS_CDEMO_SK,
    SS_HDEMO_SK,
    SS_ADDR_SK,
    SS_STORE_SK,
    SS_PROMO_SK,

    /* Transaction */
    SS_TICKET_NUMBER,

    /* Measures */
    COALESCE(SS_QUANTITY,0)                        AS QUANTITY,

    ROUND(COALESCE(SS_WHOLESALE_COST,0),2)        AS WHOLESALE_COST,
    ROUND(COALESCE(SS_LIST_PRICE,0),2)            AS LIST_PRICE,
    ROUND(COALESCE(SS_SALES_PRICE,0),2)           AS SALES_PRICE,

    ROUND(COALESCE(SS_EXT_DISCOUNT_AMT,0),2)      AS EXT_DISCOUNT_AMT,
    ROUND(COALESCE(SS_EXT_SALES_PRICE,0),2)       AS EXT_SALES_PRICE,
    ROUND(COALESCE(SS_EXT_WHOLESALE_COST,0),2)    AS EXT_WHOLESALE_COST,
    ROUND(COALESCE(SS_EXT_LIST_PRICE,0),2)        AS EXT_LIST_PRICE,
    ROUND(COALESCE(SS_EXT_TAX,0),2)               AS EXT_TAX,
    ROUND(COALESCE(SS_COUPON_AMT,0),2)            AS COUPON_AMT,

    ROUND(COALESCE(SS_NET_PAID,0),2)              AS NET_PAID,
    ROUND(COALESCE(SS_NET_PAID_INC_TAX,0),2)      AS NET_PAID_INC_TAX,
    ROUND(COALESCE(SS_NET_PROFIT,0),2)            AS NET_PROFIT,

    /* Classifications */

    CASE
        WHEN SS_COUPON_AMT > 0 THEN 'Coupon Used'
        ELSE 'No Coupon'
    END AS COUPON_USAGE,

    DEDUPED.LOAD_ID,
    DEDUPED.LOAD_DATE,
    DEDUPED.BATCH_ID

FROM DEDUPED

INNER JOIN CURATED.CUSTOMER c
    ON DEDUPED.SS_CUSTOMER_SK = c.C_CUSTOMER_SK

WHERE COALESCE(SS_QUANTITY,0) > 0
  AND COALESCE(SS_SALES_PRICE,0) >= 0;


-- create curated catalog sales

CREATE OR REPLACE TABLE CURATED.CATALOG_SALES AS

WITH DEDUPED AS (
    SELECT *
    FROM RAW.CATALOG_SALES
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY CS_ORDER_NUMBER, CS_ITEM_SK
        ORDER BY LOAD_DATE DESC
    ) = 1
)

SELECT

    /* Keys */
    CS_SOLD_DATE_SK,
    CS_SOLD_TIME_SK,
    CS_SHIP_DATE_SK,

    CS_BILL_CUSTOMER_SK,
    CS_BILL_CDEMO_SK,
    CS_BILL_HDEMO_SK,
    CS_BILL_ADDR_SK,

    CS_SHIP_CUSTOMER_SK,
    CS_SHIP_CDEMO_SK,
    CS_SHIP_HDEMO_SK,
    CS_SHIP_ADDR_SK,

    CS_CALL_CENTER_SK,
    CS_CATALOG_PAGE_SK,
    CS_SHIP_MODE_SK,
    CS_WAREHOUSE_SK,
    CS_ITEM_SK,
    CS_PROMO_SK,

    /* Transaction */
    CS_ORDER_NUMBER,

    /* Measures */
    COALESCE(CS_QUANTITY,0)                     AS QUANTITY,

    ROUND(COALESCE(CS_WHOLESALE_COST,0),2)     AS WHOLESALE_COST,
    ROUND(COALESCE(CS_LIST_PRICE,0),2)         AS LIST_PRICE,
    ROUND(COALESCE(CS_SALES_PRICE,0),2)        AS SALES_PRICE,

    ROUND(COALESCE(CS_EXT_DISCOUNT_AMT,0),2)   AS EXT_DISCOUNT_AMT,
    ROUND(COALESCE(CS_EXT_SALES_PRICE,0),2)    AS EXT_SALES_PRICE,
    ROUND(COALESCE(CS_EXT_WHOLESALE_COST,0),2) AS EXT_WHOLESALE_COST,
    ROUND(COALESCE(CS_EXT_LIST_PRICE,0),2)     AS EXT_LIST_PRICE,
    ROUND(COALESCE(CS_EXT_TAX,0),2)            AS EXT_TAX,
    ROUND(COALESCE(CS_COUPON_AMT,0),2)         AS COUPON_AMT,
    ROUND(COALESCE(CS_EXT_SHIP_COST,0),2)      AS EXT_SHIP_COST,

    ROUND(COALESCE(CS_NET_PAID,0),2)              AS NET_PAID,
    ROUND(COALESCE(CS_NET_PAID_INC_TAX,0),2)      AS NET_PAID_INC_TAX,
    ROUND(COALESCE(CS_NET_PAID_INC_SHIP,0),2)     AS NET_PAID_INC_SHIP,
    ROUND(COALESCE(CS_NET_PAID_INC_SHIP_TAX,0),2) AS NET_PAID_INC_SHIP_TAX,
    ROUND(COALESCE(CS_NET_PROFIT,0),2)            AS NET_PROFIT,
    CASE
        WHEN CS_COUPON_AMT > 0 THEN 'Coupon Used'
        ELSE 'No Coupon'
    END AS COUPON_USAGE,


    DEDUPED.LOAD_ID,
    DEDUPED.LOAD_DATE,
    DEDUPED.BATCH_ID

FROM DEDUPED

INNER JOIN CURATED.CUSTOMER c
ON DEDUPED.CS_BILL_CUSTOMER_SK = c.C_CUSTOMER_SK

WHERE COALESCE(CS_QUANTITY,0) > 0
  AND COALESCE(CS_SALES_PRICE,0) >= 0;

select *
From catalog_returns
Limit 10;